[app]
debug = false

[logger]
level = "DEBUG"

[path]
workspace = "${workspace_path}"
data = "${path.workspace}/data"
plugin = "${path.data}/${PLUGIN}"


[plugin]
prefix = "${app.name}_plugin"




[extra]

# 

[program.debug]
app.debug = true
logger.level = "DEBUG"
logger.world = "kkk"

[program.release]
logger.level = "INFO"

[program.beta]
logger.level = "INFO"