# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - '*'

permissions: 
  contents: write

jobs:
  build_wheel:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
        
      - name: Configure Git
        run: |
          git config --global user.email "gradyzhuo@ospark.org"
          git config --global user.name "Grady Zhuo"

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Release
#        uses: fnkr/github-action-ghr@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        env:
#          GHR_PATH: dist/
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
